name: xred-texttospeech-tts
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pytorch::pytorch
  - pytorch::torchaudio
  - setuptools>=65.0
  - pip>=22.0
  - pip:
    - setuptools>=65.0
    - wheel>=0.38.0
    - packaging>=21.0
    - importlib-metadata>=4.0
    - chatterbox-tts
