name: xred-speaker-identification
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy<2
  - scikit-learn
  - librosa
  - sox
  - pytorch::pytorch
  - pytorch::torchaudio
  - pip:
      - speechbrain
      - silero-vad
      - python-dotenv
